### PR TITLE
Cmake-based setup scripts

### PR DESCRIPTION
**Pull request by stlemme**

### CODE REVIEW

**Comment by leissa** [comment]
From my side this looks good. Just two things:
* are the DFKI-URLs available for anyone including users not within the university network?
* so when do we use ```UPPER_CASE``` and ```snake_case``` for cmake stuff? We are a inconsistent here across several anydsl-projects. I'd suggest to agree on some style now. I'd prefer ```snake_case``` for all cmake-builtins and ```UPPER_CASE``` for cmake-variables. 
* Also, is it required/considered good practice by cmake to have spaces around parentheses? Like this:
    ```cmake
    set ( foo bar )
    ```
    why not just this:
    ```cmake
    set(foo bar)
    ```

**Comment by richardmembarth** [comment]
We should go for:
```cmake
set(foo bar)
```
We have this for all repos apart from Impala and Thorin for historical reasons.

DFKI cloud is also available from outside, but I agree that we should pull this from the official sites. Actually the scripts include two variants, once downloading from the official sites, once a local copy on DFKI cloud ... so just use the official site.

**Comment by richardmembarth** [comment]
What's actually the purpose of those CMake files?
They are nowhere used?

**Comment by leissa** [comment]
I thought they are an alternative for our setup script which also works under windows.

**Comment by richardmembarth** [comment]
I guess this is the plan, but there is no main CMakeLists.txt to setup everything.

**Comment by richardmembarth** [comment]
So we can't test this.

**Comment by leissa** [comment]
good point :)
@stlemme: Can you enlighten us?

**Comment by leissa** [comment]
regarding coding style:
https://cmake.org/Wiki/CMake:How_To_Find_Libraries

**Comment by stlemme** [comment]
The cmake scripts are meant for script mode of cmake, i.e. cmake -P setup.cmake
For further usage refer to commit 890baf1

**Comment by richardmembarth** [comment]
Ok, I see.

So I see the following problems:
- out of tree usage doesn't work
- build fails after some time:
```
anydsl/anydsl/thorin/build/lib/libthorin.so: undefined reference to `typeinfo for llvm::Instruction'
anydsl/anydsl/thorin/build/lib/libthorin.so: undefined reference to `typeinfo for llvm::UnaryInstruction'
anydsl/anydsl/thorin/build/lib/libthorin.so: undefined reference to `typeinfo for llvm::CmpInst'
```
- CMake coding style
- move cmake helper files to cmake folder
- remove DFKI llvm dowloads
- documentation

**Pull request merged**
